/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as proposalRelayerSol from "./ProposalRelayer.sol";
export type { proposalRelayerSol };
export type { SnapshotXL1Executor } from "./SnapshotXL1Executor";
