/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface SnapshotXL1ExecutorInterface extends utils.Interface {
  functions: {
    "DOMAIN_SEPARATOR_TYPEHASH()": FunctionFragment;
    "TRANSACTION_TYPEHASH()": FunctionFragment;
    "changeL2ExecutionRelayer(uint256)": FunctionFragment;
    "disableSpace(uint256)": FunctionFragment;
    "enableSpace(uint256)": FunctionFragment;
    "execute(uint256,uint256,uint256,uint256,address[],uint256[],bytes[],uint8[])": FunctionFragment;
    "generateTransactionHashData(address,uint256,bytes,uint8,uint256)": FunctionFragment;
    "getGuard()": FunctionFragment;
    "getTransactionHash(address,uint256,bytes,uint8)": FunctionFragment;
    "guard()": FunctionFragment;
    "isSpaceEnabled(uint256)": FunctionFragment;
    "l2ExecutionRelayer()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setGuard(address)": FunctionFragment;
    "setUp(bytes)": FunctionFragment;
    "starknetCore()": FunctionFragment;
    "target()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DOMAIN_SEPARATOR_TYPEHASH"
      | "TRANSACTION_TYPEHASH"
      | "changeL2ExecutionRelayer"
      | "disableSpace"
      | "enableSpace"
      | "execute"
      | "generateTransactionHashData"
      | "getGuard"
      | "getTransactionHash"
      | "guard"
      | "isSpaceEnabled"
      | "l2ExecutionRelayer"
      | "owner"
      | "renounceOwnership"
      | "setGuard"
      | "setUp"
      | "starknetCore"
      | "target"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TRANSACTION_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeL2ExecutionRelayer",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "disableSpace",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "enableSpace",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "generateTransactionHashData",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "getGuard", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTransactionHash",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "guard", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isSpaceEnabled",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "l2ExecutionRelayer",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGuard",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setUp",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "starknetCore",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "target", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TRANSACTION_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeL2ExecutionRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disableSpace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableSpace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "generateTransactionHashData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGuard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "guard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isSpaceEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "l2ExecutionRelayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setGuard", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setUp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "starknetCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "target", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "ChangedGuard(address)": EventFragment;
    "ChangedL2ExecutionRelayer(uint256)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "ProposalCancelled(uint256)": EventFragment;
    "ProposalExecuted(uint256)": EventFragment;
    "ProposalReceived(uint256)": EventFragment;
    "SnapshotXL1ExecutorSetUpComplete(address,address,address,uint256,address)": EventFragment;
    "SpaceDisabled(uint256)": EventFragment;
    "SpaceEnabled(uint256)": EventFragment;
    "TransactionExecuted(uint256,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ChangedGuard"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ChangedL2ExecutionRelayer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalReceived"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "SnapshotXL1ExecutorSetUpComplete"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SpaceDisabled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SpaceEnabled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransactionExecuted"): EventFragment;
}

export interface ChangedGuardEventObject {
  guard: string;
}
export type ChangedGuardEvent = TypedEvent<[string], ChangedGuardEventObject>;

export type ChangedGuardEventFilter = TypedEventFilter<ChangedGuardEvent>;

export interface ChangedL2ExecutionRelayerEventObject {
  _l2ExecutionRelayer: BigNumber;
}
export type ChangedL2ExecutionRelayerEvent = TypedEvent<
  [BigNumber],
  ChangedL2ExecutionRelayerEventObject
>;

export type ChangedL2ExecutionRelayerEventFilter =
  TypedEventFilter<ChangedL2ExecutionRelayerEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface ProposalCancelledEventObject {
  proposalIndex: BigNumber;
}
export type ProposalCancelledEvent = TypedEvent<
  [BigNumber],
  ProposalCancelledEventObject
>;

export type ProposalCancelledEventFilter =
  TypedEventFilter<ProposalCancelledEvent>;

export interface ProposalExecutedEventObject {
  proposalIndex: BigNumber;
}
export type ProposalExecutedEvent = TypedEvent<
  [BigNumber],
  ProposalExecutedEventObject
>;

export type ProposalExecutedEventFilter =
  TypedEventFilter<ProposalExecutedEvent>;

export interface ProposalReceivedEventObject {
  proposalIndex: BigNumber;
}
export type ProposalReceivedEvent = TypedEvent<
  [BigNumber],
  ProposalReceivedEventObject
>;

export type ProposalReceivedEventFilter =
  TypedEventFilter<ProposalReceivedEvent>;

export interface SnapshotXL1ExecutorSetUpCompleteEventObject {
  initiator: string;
  _owner: string;
  _target: string;
  _l2ExecutionRelayer: BigNumber;
  _starknetCore: string;
}
export type SnapshotXL1ExecutorSetUpCompleteEvent = TypedEvent<
  [string, string, string, BigNumber, string],
  SnapshotXL1ExecutorSetUpCompleteEventObject
>;

export type SnapshotXL1ExecutorSetUpCompleteEventFilter =
  TypedEventFilter<SnapshotXL1ExecutorSetUpCompleteEvent>;

export interface SpaceDisabledEventObject {
  space: BigNumber;
}
export type SpaceDisabledEvent = TypedEvent<
  [BigNumber],
  SpaceDisabledEventObject
>;

export type SpaceDisabledEventFilter = TypedEventFilter<SpaceDisabledEvent>;

export interface SpaceEnabledEventObject {
  space: BigNumber;
}
export type SpaceEnabledEvent = TypedEvent<
  [BigNumber],
  SpaceEnabledEventObject
>;

export type SpaceEnabledEventFilter = TypedEventFilter<SpaceEnabledEvent>;

export interface TransactionExecutedEventObject {
  proposalIndex: BigNumber;
  txHash: string;
}
export type TransactionExecutedEvent = TypedEvent<
  [BigNumber, string],
  TransactionExecutedEventObject
>;

export type TransactionExecutedEventFilter =
  TypedEventFilter<TransactionExecutedEvent>;

export interface SnapshotXL1Executor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SnapshotXL1ExecutorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DOMAIN_SEPARATOR_TYPEHASH(overrides?: CallOverrides): Promise<[string]>;

    TRANSACTION_TYPEHASH(overrides?: CallOverrides): Promise<[string]>;

    changeL2ExecutionRelayer(
      _l2ExecutionRelayer: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    disableSpace(
      space: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    enableSpace(
      space: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    execute(
      callerAddress: PromiseOrValue<BigNumberish>,
      proposalOutcome: PromiseOrValue<BigNumberish>,
      executionHashLow: PromiseOrValue<BigNumberish>,
      executionHashHigh: PromiseOrValue<BigNumberish>,
      _tos: PromiseOrValue<string>[],
      _values: PromiseOrValue<BigNumberish>[],
      _data: PromiseOrValue<BytesLike>[],
      _operations: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    generateTransactionHashData(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string] & { txHashData: string }>;

    getGuard(overrides?: CallOverrides): Promise<[string] & { _guard: string }>;

    getTransactionHash(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string] & { txHash: string }>;

    guard(overrides?: CallOverrides): Promise<[string]>;

    isSpaceEnabled(
      space: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    l2ExecutionRelayer(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setGuard(
      _guard: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setUp(
      initParams: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    starknetCore(overrides?: CallOverrides): Promise<[string]>;

    target(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  DOMAIN_SEPARATOR_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  TRANSACTION_TYPEHASH(overrides?: CallOverrides): Promise<string>;

  changeL2ExecutionRelayer(
    _l2ExecutionRelayer: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  disableSpace(
    space: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  enableSpace(
    space: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  execute(
    callerAddress: PromiseOrValue<BigNumberish>,
    proposalOutcome: PromiseOrValue<BigNumberish>,
    executionHashLow: PromiseOrValue<BigNumberish>,
    executionHashHigh: PromiseOrValue<BigNumberish>,
    _tos: PromiseOrValue<string>[],
    _values: PromiseOrValue<BigNumberish>[],
    _data: PromiseOrValue<BytesLike>[],
    _operations: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  generateTransactionHashData(
    to: PromiseOrValue<string>,
    value: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    operation: PromiseOrValue<BigNumberish>,
    nonce: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getGuard(overrides?: CallOverrides): Promise<string>;

  getTransactionHash(
    to: PromiseOrValue<string>,
    value: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    operation: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  guard(overrides?: CallOverrides): Promise<string>;

  isSpaceEnabled(
    space: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  l2ExecutionRelayer(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setGuard(
    _guard: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setUp(
    initParams: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  starknetCore(overrides?: CallOverrides): Promise<string>;

  target(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    DOMAIN_SEPARATOR_TYPEHASH(overrides?: CallOverrides): Promise<string>;

    TRANSACTION_TYPEHASH(overrides?: CallOverrides): Promise<string>;

    changeL2ExecutionRelayer(
      _l2ExecutionRelayer: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    disableSpace(
      space: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    enableSpace(
      space: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    execute(
      callerAddress: PromiseOrValue<BigNumberish>,
      proposalOutcome: PromiseOrValue<BigNumberish>,
      executionHashLow: PromiseOrValue<BigNumberish>,
      executionHashHigh: PromiseOrValue<BigNumberish>,
      _tos: PromiseOrValue<string>[],
      _values: PromiseOrValue<BigNumberish>[],
      _data: PromiseOrValue<BytesLike>[],
      _operations: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    generateTransactionHashData(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getGuard(overrides?: CallOverrides): Promise<string>;

    getTransactionHash(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    guard(overrides?: CallOverrides): Promise<string>;

    isSpaceEnabled(
      space: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    l2ExecutionRelayer(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setGuard(
      _guard: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setUp(
      initParams: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    starknetCore(overrides?: CallOverrides): Promise<string>;

    target(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ChangedGuard(address)"(guard?: null): ChangedGuardEventFilter;
    ChangedGuard(guard?: null): ChangedGuardEventFilter;

    "ChangedL2ExecutionRelayer(uint256)"(
      _l2ExecutionRelayer?: null
    ): ChangedL2ExecutionRelayerEventFilter;
    ChangedL2ExecutionRelayer(
      _l2ExecutionRelayer?: null
    ): ChangedL2ExecutionRelayerEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "ProposalCancelled(uint256)"(
      proposalIndex?: null
    ): ProposalCancelledEventFilter;
    ProposalCancelled(proposalIndex?: null): ProposalCancelledEventFilter;

    "ProposalExecuted(uint256)"(
      proposalIndex?: null
    ): ProposalExecutedEventFilter;
    ProposalExecuted(proposalIndex?: null): ProposalExecutedEventFilter;

    "ProposalReceived(uint256)"(
      proposalIndex?: null
    ): ProposalReceivedEventFilter;
    ProposalReceived(proposalIndex?: null): ProposalReceivedEventFilter;

    "SnapshotXL1ExecutorSetUpComplete(address,address,address,uint256,address)"(
      initiator?: PromiseOrValue<string> | null,
      _owner?: PromiseOrValue<string> | null,
      _target?: null,
      _l2ExecutionRelayer?: null,
      _starknetCore?: null
    ): SnapshotXL1ExecutorSetUpCompleteEventFilter;
    SnapshotXL1ExecutorSetUpComplete(
      initiator?: PromiseOrValue<string> | null,
      _owner?: PromiseOrValue<string> | null,
      _target?: null,
      _l2ExecutionRelayer?: null,
      _starknetCore?: null
    ): SnapshotXL1ExecutorSetUpCompleteEventFilter;

    "SpaceDisabled(uint256)"(space?: null): SpaceDisabledEventFilter;
    SpaceDisabled(space?: null): SpaceDisabledEventFilter;

    "SpaceEnabled(uint256)"(space?: null): SpaceEnabledEventFilter;
    SpaceEnabled(space?: null): SpaceEnabledEventFilter;

    "TransactionExecuted(uint256,bytes32)"(
      proposalIndex?: null,
      txHash?: null
    ): TransactionExecutedEventFilter;
    TransactionExecuted(
      proposalIndex?: null,
      txHash?: null
    ): TransactionExecutedEventFilter;
  };

  estimateGas: {
    DOMAIN_SEPARATOR_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;

    TRANSACTION_TYPEHASH(overrides?: CallOverrides): Promise<BigNumber>;

    changeL2ExecutionRelayer(
      _l2ExecutionRelayer: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    disableSpace(
      space: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    enableSpace(
      space: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    execute(
      callerAddress: PromiseOrValue<BigNumberish>,
      proposalOutcome: PromiseOrValue<BigNumberish>,
      executionHashLow: PromiseOrValue<BigNumberish>,
      executionHashHigh: PromiseOrValue<BigNumberish>,
      _tos: PromiseOrValue<string>[],
      _values: PromiseOrValue<BigNumberish>[],
      _data: PromiseOrValue<BytesLike>[],
      _operations: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    generateTransactionHashData(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGuard(overrides?: CallOverrides): Promise<BigNumber>;

    getTransactionHash(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    guard(overrides?: CallOverrides): Promise<BigNumber>;

    isSpaceEnabled(
      space: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    l2ExecutionRelayer(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setGuard(
      _guard: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setUp(
      initParams: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    starknetCore(overrides?: CallOverrides): Promise<BigNumber>;

    target(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DOMAIN_SEPARATOR_TYPEHASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TRANSACTION_TYPEHASH(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    changeL2ExecutionRelayer(
      _l2ExecutionRelayer: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    disableSpace(
      space: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    enableSpace(
      space: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    execute(
      callerAddress: PromiseOrValue<BigNumberish>,
      proposalOutcome: PromiseOrValue<BigNumberish>,
      executionHashLow: PromiseOrValue<BigNumberish>,
      executionHashHigh: PromiseOrValue<BigNumberish>,
      _tos: PromiseOrValue<string>[],
      _values: PromiseOrValue<BigNumberish>[],
      _data: PromiseOrValue<BytesLike>[],
      _operations: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    generateTransactionHashData(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGuard(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTransactionHash(
      to: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      operation: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    guard(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isSpaceEnabled(
      space: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    l2ExecutionRelayer(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setGuard(
      _guard: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setUp(
      initParams: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    starknetCore(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    target(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
