/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  StarkNetCommit,
  StarkNetCommitInterface,
} from "../../../../contracts/ethereum/StarkNetCommit/StarkNetCommit";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract MockStarknetMessaging",
        name: "_starknetCore",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "starknetAuthenticator",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_hash",
        type: "uint256",
      },
    ],
    name: "commit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "starknetCore",
    outputs: [
      {
        internalType: "contract MockStarknetMessaging",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60a060405234801561001057600080fd5b5060405161032238038061032283398101604081905261002f91610040565b6001600160a01b0316608052610070565b60006020828403121561005257600080fd5b81516001600160a01b038116811461006957600080fd5b9392505050565b608051610291610091600039600081816040015261011301526102916000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806339e730ab1461003b5780635bf56bc41461007e575b600080fd5b6100627f000000000000000000000000000000000000000000000000000000000000000081565b6040516001600160a01b03909116815260200160405180910390f35b61009161008c3660046101b5565b610093565b005b604080516002808252606082018352600092602083019080368337019050509050336001600160a01b0316816000815181106100d1576100d16101d7565b60200260200101818152505081816001815181106100f1576100f16101d7565b6020908102919091010152604051633e3aa6c560e01b81526001600160a01b037f00000000000000000000000000000000000000000000000000000000000000001690633e3aa6c59061016c9086907f017dd2cbe677d6dda22dd4a01edec54ba307cd2b1f7d130707ba5a29cc019c1d9086906004016101ed565b6020604051808303816000875af115801561018b573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101af9190610242565b50505050565b600080604083850312156101c857600080fd5b50508035926020909101359150565b634e487b7160e01b600052603260045260246000fd5b6000606082018583526020858185015260606040850152818551808452608086019150828701935060005b8181101561023457845183529383019391830191600101610218565b509098975050505050505050565b60006020828403121561025457600080fd5b505191905056fea2646970667358221220d964686c4cf9a80b92fd2d195ef743fe64a271dca6329ff65fea06edbe77b4af64736f6c63430008110033";

type StarkNetCommitConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: StarkNetCommitConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class StarkNetCommit__factory extends ContractFactory {
  constructor(...args: StarkNetCommitConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _starknetCore: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<StarkNetCommit> {
    return super.deploy(
      _starknetCore,
      overrides || {}
    ) as Promise<StarkNetCommit>;
  }
  override getDeployTransaction(
    _starknetCore: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_starknetCore, overrides || {});
  }
  override attach(address: string): StarkNetCommit {
    return super.attach(address) as StarkNetCommit;
  }
  override connect(signer: Signer): StarkNetCommit__factory {
    return super.connect(signer) as StarkNetCommit__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StarkNetCommitInterface {
    return new utils.Interface(_abi) as StarkNetCommitInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StarkNetCommit {
    return new Contract(address, _abi, signerOrProvider) as StarkNetCommit;
  }
}
