/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IStarknetMessaging,
  IStarknetMessagingInterface,
} from "../../../../contracts/ethereum/TestContracts/IStarknetMessaging";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "from_address",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to_address",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "payload",
        type: "uint256[]",
      },
    ],
    name: "ConsumedMessageToL1",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from_address",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "to_address",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "selector",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "payload",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
    ],
    name: "ConsumedMessageToL2",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "from_address",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to_address",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "payload",
        type: "uint256[]",
      },
    ],
    name: "LogMessageToL1",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from_address",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "to_address",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "selector",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "payload",
        type: "uint256[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
    ],
    name: "LogMessageToL2",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fromAddress",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "payload",
        type: "uint256[]",
      },
    ],
    name: "consumeMessageFromL2",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "to_address",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "selector",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "payload",
        type: "uint256[]",
      },
    ],
    name: "sendMessageToL2",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IStarknetMessaging__factory {
  static readonly abi = _abi;
  static createInterface(): IStarknetMessagingInterface {
    return new utils.Interface(_abi) as IStarknetMessagingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStarknetMessaging {
    return new Contract(address, _abi, signerOrProvider) as IStarknetMessaging;
  }
}
