/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../common";

export interface L1MessagesSenderInterface extends utils.Interface {
  functions: {
    "l2RecipientAddr()": FunctionFragment;
    "sendExactParentHashToL2(uint256)": FunctionFragment;
    "sendLatestParentHashToL2()": FunctionFragment;
    "starknetCore()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "l2RecipientAddr"
      | "sendExactParentHashToL2"
      | "sendLatestParentHashToL2"
      | "starknetCore"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "l2RecipientAddr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendExactParentHashToL2",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "sendLatestParentHashToL2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "starknetCore",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "l2RecipientAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendExactParentHashToL2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendLatestParentHashToL2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "starknetCore",
    data: BytesLike
  ): Result;

  events: {};
}

export interface L1MessagesSender extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: L1MessagesSenderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    l2RecipientAddr(overrides?: CallOverrides): Promise<[BigNumber]>;

    sendExactParentHashToL2(
      blockNumber_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sendLatestParentHashToL2(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    starknetCore(overrides?: CallOverrides): Promise<[string]>;
  };

  l2RecipientAddr(overrides?: CallOverrides): Promise<BigNumber>;

  sendExactParentHashToL2(
    blockNumber_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sendLatestParentHashToL2(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  starknetCore(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    l2RecipientAddr(overrides?: CallOverrides): Promise<BigNumber>;

    sendExactParentHashToL2(
      blockNumber_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    sendLatestParentHashToL2(overrides?: CallOverrides): Promise<void>;

    starknetCore(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    l2RecipientAddr(overrides?: CallOverrides): Promise<BigNumber>;

    sendExactParentHashToL2(
      blockNumber_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sendLatestParentHashToL2(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    starknetCore(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    l2RecipientAddr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sendExactParentHashToL2(
      blockNumber_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sendLatestParentHashToL2(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    starknetCore(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
